/*
 * CardDescriptions.java
 *
 */
package brawlcardgame;

import brawlcardgame.state.BrawlGameState;
import brawlcardgame.state.PlayerID;
import java.util.HashMap;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;
import org.jdesktop.application.Action;

/**
 *
 * @author Quine
 */
public class BrawlCardDescriptionsBox extends javax.swing.JDialog {

   private static final long serialVersionUID = 1L;

   /** Creates new form CardDescriptions */
   public BrawlCardDescriptionsBox() {
      initComponents();
   }

   public BrawlCardDescriptionsBox(java.awt.Frame parent, BrawlGameState state) {
      super(parent);
      initComponents();
      getRootPane().setDefaultButton(closeButton);

      // Add the descriptions
      HashMap<Class<? extends BrawlCard>, BrawlCard> cards = new HashMap<Class<? extends BrawlCard>, BrawlCard>();
      HTMLEditorKit kit = new HTMLEditorKit();
      HTMLDocument doc = new HTMLDocument();
      cardDescriptions.setEditorKit(kit);
      cardDescriptions.setDocument(doc);
      
      try {
         // Header for the field
         kit.insertHTML(doc, doc.getLength(), "<font size='5'>Description of Each Card in the Decks</font><br><br>", 0, 0, null);
      } catch (Exception ex) {
         System.out.println("This should not be possible but java forces me to catch it");
      }
      
      // Get each card type and put it into the hash
      for (PlayerID player : PlayerID.values()) {
         for (BrawlCard card : state.getPlayers().get(player).getDeck().getCards()) {
            cards.put(card.getClass(), card);
         }
      }
      
      // Add the descriptions of each card type to the view
      for (BrawlCard card : cards.values()) {
         try {
            kit.insertHTML(doc, doc.getLength(), "<font size='4'>" + card.display() + ": </font><br>" 
                    + card.getDescription() 
                    + "<br><br>", 0, 0, null);
         } catch (Exception ex) {
            System.out.println("Error printing description for card" + card.display());
         }
      }
   }

   @Action
   public void closeDescriptionsBox() {
      dispose();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      cardDescriptions = new javax.swing.JTextPane();
      closeButton = new javax.swing.JButton();

      setName("Form"); // NOI18N

      jScrollPane1.setName("jScrollPane1"); // NOI18N

      cardDescriptions.setEditable(false);
      cardDescriptions.setName("cardDescriptions"); // NOI18N
      jScrollPane1.setViewportView(cardDescriptions);

      javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(brawlcardgame.BrawlCardGameApp.class).getContext().getActionMap(BrawlCardDescriptionsBox.class, this);
      closeButton.setAction(actionMap.get("closeDescriptionsBox")); // NOI18N
      org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(brawlcardgame.BrawlCardGameApp.class).getContext().getResourceMap(BrawlCardDescriptionsBox.class);
      closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
      closeButton.setName("closeButton"); // NOI18N

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               .add(layout.createSequentialGroup()
                  .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                  .addContainerGap())
               .add(layout.createSequentialGroup()
                  .add(closeButton)
                  .add(16, 16, 16))))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
            .add(9, 9, 9)
            .add(closeButton)
            .add(17, 17, 17))
      );
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextPane cardDescriptions;
   private javax.swing.JButton closeButton;
   private javax.swing.JScrollPane jScrollPane1;
   // End of variables declaration//GEN-END:variables
}
